[package]
name = "pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
usvg = "0.45.1"
vello_svg = "0.8.0"
xilem = {path = "./xilem/xilem"}
xilem_core = "0.4.0"
